/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Achievement } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_pop',
    title: 'First Pop',
    description: 'Pop your very first bubble wrap bubble. Satisfying!',
    iconName: 'Sparkles',
    category: 'bubble',
    targetField: 'totalPops',
    targetValue: 1,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: '100_pops',
    title: 'Bubble Enthusiast',
    description: 'Pop 100 bubbles. Feeling relaxed already.',
    iconName: 'Award',
    category: 'bubble',
    targetField: 'totalPops',
    targetValue: 100,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: '1000_pops',
    title: 'Bubble Legend',
    description: 'Pop 1,000 bubbles. Absolute sensory perfection.',
    iconName: 'Zap',
    category: 'bubble',
    targetField: 'totalPops',
    targetValue: 1000,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'first_smash',
    title: 'First Smash',
    description: 'Smash your first item in the destruction lab!',
    iconName: 'Hammer',
    category: 'smash',
    targetField: 'totalSmashes',
    targetValue: 1,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: '100_smashes',
    title: 'Smash Master',
    description: 'Demolish 100 items. Ultimate stress venting complete.',
    iconName: 'Flame',
    category: 'smash',
    targetField: 'totalSmashes',
    targetValue: 100,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'first_spin',
    title: 'First Spin',
    description: 'Swipe to rotate a modular fidget spinner.',
    iconName: 'RotateCw',
    category: 'spinner',
    targetField: 'totalSpins',
    targetValue: 1,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: '50_spins',
    title: 'Master Spinner',
    description: 'Spin 50 times. Inertia is your best companion.',
    iconName: 'TrendingUp',
    category: 'spinner',
    targetField: 'totalSpins',
    targetValue: 50,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'rages_1',
    title: 'Furious Tap',
    description: 'Hit the rage button once to vent custom energy.',
    iconName: 'Zap',
    category: 'rage',
    targetField: 'totalRageClicks',
    targetValue: 1,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'rages_100',
    title: 'Rage Monster',
    description: 'Hit the rage button 100 times. Getting warm...',
    iconName: 'Flame',
    category: 'rage',
    targetField: 'totalRageClicks',
    targetValue: 100,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'rages_1000',
    title: 'Super Saiyan Tap',
    description: '1,000 rage clicks! Total combustion unlocked.',
    iconName: 'Volume2',
    category: 'rage',
    targetField: 'totalRageClicks',
    targetValue: 1000,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'rages_5000',
    title: 'Zen Ascension',
    description: 'Pressed 5,000 times. You have found ultimate inner peace.',
    iconName: 'Sparkles',
    category: 'rage',
    targetField: 'totalRageClicks',
    targetValue: 5000,
    unlocked: false,
    unlockedAt: null,
  }
];
